### PR TITLE
Bump node_exporter to 1.1.0

### PR DESCRIPTION
**Pull request by paulfantom**
Needed by https://github.com/openshift/cluster-monitoring-operator/pull/1044

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@paulfantom i believe you mentioned some bigger changes upstream, are we somehow affected with potentially breaking changes?

**Comment by paulfantom** [comment]
> are we somehow affected with potentially breaking changes?

nope

**Comment by paulfantom** [comment]
/hold

putting on hold as there is something broken and this PR can wait

**Comment by paulfantom** [comment]
Closing as node_exporter 1.1.1 was released and PR with that version is in #84

**Pull request closed without merging**
