### PR TITLE
OCPBUGS-6003: Remove metrics of offline CPUs in CPU collector

### PR DESCRIPTION
**Pull request by raptorsun**
Cherry pick 2 commits from upstream to fix the bug OCPBUGS-6003.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/hold

node_exporter logs show errors

`ts=2023-05-03T14:24:52.112Z caller=collector.go:169 level=error msg="collector failed" name=netclass duration_seconds=0.002129437 err="could not get net class info: failed to read file \"/host/sys/class/net/eth0/name_assign_type\": invalid argument"`

**Comment by raptorsun** [comment]
> 

The underlying host does not support reading several properties such as `name_assign_type`, `duplex` of some NICs. 
The error is not related to Node Exporter.

```
sh-4.4$ cd /host/sys/class/net/ens5/
sh-4.4$ ls
addr_assign_type  broadcast        carrier_down_count  dev_port  duplex             ifalias  link_mode  name_assign_type      operstate       phys_switch_id  queues      subsystem  tx_queue_len  upper_ovs-system
addr_len          carrier          carrier_up_count    device    flags              ifindex  master     napi_defer_hard_irqs  phys_port_id    power           speed       testing    type
address           carrier_changes  dev_id              dormant   gro_flush_timeout  iflink   mtu        netdev_group          phys_port_name  proto_down      statistics  threaded   uevent
sh-4.4$ cat duplex 
cat: duplex: Invalid argument
sh-4.4$ ls -l duplex 
-r--r--r--. 1 root root 4096 May  4 16:06 duplex
sh-4.4$ 
```

**Comment by raptorsun** [comment]
/close 

upgrade node exporter to v1.60+ will bring us the fix.

**Pull request closed without merging**
