### PR TITLE
Bug 1984030: netclass: retrieve interface names and filter before parsing

### PR DESCRIPTION
**Pull request by jan--f**
This is a cherry-pick of https://github.com/prometheus/node_exporter/pull/2033

### CODE REVIEW

**Comment by simonpasquier** [comment]
It might be worth creating a BZ so we can backport it on 4.8 later on (the CPU reduction with the patch is quite important for baremetal machines).

**Comment by jan--f** [comment]
/retitle Bug 1984030: netclass: retrieve interface names and filter before parsing

**Pull request merged**
