### PR TITLE
Bug 1785594: backport cpu info metric

### PR DESCRIPTION
**Pull request by pgier**

### CODE REVIEW

**Comment by LiliC** [comment]
For some reason the bugzilla is in modified state

**Comment by lilic** [comment]
/hold

something is wrong with the tests it seems, 9 times does not seem like a flake, so putting on hold. @pgier

**Comment by crawford** [comment]
@pgier can you take another look at this?

**Comment by pgier** [comment]
The test failures don't seem to be related to node_exporter AFAICT.
Will try the tests again tomorrow and then investigate further.

**Comment by eparis** [comment]
what is the absolute critical reason to do this at all in 4.1? It's basically EOL. Should we just close this and the bug?

**Comment by s-urbaniak** [comment]
agreed, let's close the BZ and the PR, it is fixed for >=4.2 as per https://bugzilla.redhat.com/show_bug.cgi?id=1789260

**Pull request closed without merging**
