### PR TITLE
Rebase to v1.0.1

### PR DESCRIPTION
**Pull request by pgier**
Update node_exporter to latest version.  There are a few breaking changes in this release, but AFAICT none of them will affect the monitoring deployment in openshift.

### CODE REVIEW

**Comment by pgier** [comment]
Currently failing due to dependency on go1.14

**Comment by paulfantom** [comment]
Seems like there are some issue with downloading promu in container build.

**Comment by paulfantom** [comment]
> Currently failing due to dependency on go1.14

We can enforce go version in https://github.com/openshift/release/blob/master/ci-operator/config/openshift/node_exporter/openshift-node_exporter-release-4.6.yaml#L12

**Comment by simonpasquier** [comment]
Do we have 1.14 available in ART builds?

**Comment by paulfantom** [comment]
Apparently this still isn't enabled. :shrug: 

I [raised the issue with DPTP](https://coreos.slack.com/archives/CBN38N3MW/p1591082882397000), but there is no answer for now.

**Comment by lilic** [comment]
@pgier  We should make sure that the telemetry metrics we are sending and all recording rules and alerts still work, or we adjust those, might be good to add those telemetry to origin e2e tests? At least the ones we provide via node_exporter wdyt?

**Comment by pgier** [comment]
I created a diff of the metrics before and after merging v1.0.1 and review the changes to see if anything will affect our metrics in Openshift, and I didn't find any incompatibilities.  I also read the list of breaking changes in the changelog, and there also do not appear to be any incompatibilities with our usage.

**Comment by paulfantom** [comment]
We cannot merge it due to lack of golang 1.14 in OpenShift.

/hold

**Comment by paulfantom** [comment]
@pgier We need to adjust Dockerfile.ocp in this PR before merging it. Simple change from https://github.com/openshift/node_exporter/pull/65 should allow properly building it using go 1.14 tooling.

**Comment by pgier** [comment]
@paulfantom I cherry-picked your commit from the the other PR, so if the tests pass here, I guess you can close that one?

**Pull request merged**
