### PR TITLE
OCPBUGS-6311: addressing vulnerability GO-2022-1144

### PR DESCRIPTION
**Pull request by raptorsun**
upgrade package golang.org/x/net to v0.5.0

### CODE REVIEW

**Review by JoaoBraveCoding — COMMENTED** [review]
I'm not familiar with fixing CVE but shouldn't we open a PR for this upstream and have it merge through there?

Apart from this lgtm

**Comment by raptorsun** [comment]
> I'm not familiar with fixing CVE but shouldn't we open a PR for this upstream and have it merge through there?
> 
> Apart from this lgtm

Yup, I will submit a PR to upstream, too 👍

**Comment by simonpasquier** [comment]
upstream is already patched from what I can tell but there's no official tag with the fix.

**Comment by raptorsun** [comment]
> upstream is already patched from what I can tell but there's no official tag with the fix.

Just checked. 
Our downstream uses a newer version (0.5.0) of `x/net` than [upstream(0.4.0)](https://github.com/prometheus/node_exporter/blob/master/go.mod#L54).

**Pull request merged**
